### ISSUE TITLE
How do I make him register?

### ISSUE THREAD

**Issue by manavortex** [clux/cleverbot-irc#12]
Hi clux, 
I'm not very good with javascript, unfortunately, and after a day or two of trying around I've decided just to ask. 
If I want the bot to send a nickserv command to the server on connect, how would I achieve that?

Thanks already.

**Comment by clux** [comment]
Hey,

Think that would be the domain of the [irc](https://www.npmjs.com/package/irc) module which [irc-stream](https://www.npmjs.com/package/irc-stream) uses.

If you can get the irc module to do that (documentation says you can send raw commands), then you can get irc-stream to do that before you connect the things to gu in [cleverbots entrypoint](https://github.com/clux/cleverbot-irc/blob/master/irc.js). irc-stream exposes the `irc` instance on `ircStream.bot` so you can use that as an `irc` instance and send the corresponding raw command there.

I think that's right anyway. If that works please let me know, and I can integrate it :)

**Comment by manavortex** [comment]
Hey there, 
I tried to throw it in the .clvr.json's "irc" block, but that didn't do anything. Funny thing is, if it's the last parameter, the config can't be read and the bot falls back on the default conf. :>
It would be awesome to be able to somehow dig on the "on connect"-event. I mean, I could have him message nickserv upon joining a channel simply by send("nickserv", "identify password"), and it would also offer further customisation options. Do you think that would work?

thanks a lot :)

**Comment by clux** [comment]
>  Funny thing is, if it's the last parameter, the config can't be read and the bot falls back on the default conf. :>

That sounds weird, got any code that I can try for that?

> It would be awesome to be able to somehow dig on the "on connect"-event. 

Yeah, you should just be able to

```js
ircStream.bot.on('registered', function() { ircStream.bot.send('nickserv', 'pw'); });
```

in the entry point.

As far as extending cleverbots config for something like that - not sure yet. Maybe it could be an extra function to pass to irc-stream, but the config would have to be json. If the pasword sent to a bot is a sufficiently generic pattern, then probably, but depends how much customization is needed.

**Comment by manavortex** [comment]
Hey there, 
thank you for your help so far!
Unfortunately, I haven't been managing to get this to work yet. This is how irc.js looks for me now:

```
#!/usr/bin/env node
var pw='mysecretpass'

var cfg = require(require('confortable')('.clvr.json', process.cwd()));
var ircStream = require('irc-stream')(cfg.server, cfg.name, cfg.irc, cfg.stream);

ircStream.bot.on('registered', function() {
        ircStream.bot.send('nickserv', pw);
        ircStream.bot.send('manavortex', 'hi');
});

var gu = require('./').gu();
require('sulfur').absorb(gu.log, 'clvrbot');

ircStream.pipe(gu).pipe(ircStream)
```

I don't get any 'hi', though. What exactly am I doing wrong here?
Great job with this, btw. I've been trying to get the cleverbot to work for quite some time myself and have miserably failed. I'm considering wrapping this up in ruby somehow, it should be able to hold a javascript internally somehow... 

![alt text](http://s.quickmeme.com/img/da/da5e0673d23ddcb208a688dae038e3d8c8a5c2d71f177eae25074f430400a40e.jpg "First world problem")

Also, while I'm at it - can the formatting and the triggers be changed? If yes, where? 
The bot always replies with nick: reply, where can that be altered?
Where is the trigger processed, can I make the bot react on other words too?

**Comment by clux** [comment]
`.send` seems to be for raw commands though, `.say` may be useful if you want to say something. Not actually sure how you are meant to register with nickserv, but you may find this [nickserv](https://www.npmjs.com/package/nickserv) library useful. You should just be able attach it to `ircStream.bot`.

The [stream key in the config file](https://github.com/clux/cleverbot-irc/blob/ed7f1ba12fb56b49409a2f092b621195b0af271a/.clvr.json#L9-L12) controls how it responds. See [irc-stream options](https://github.com/clux/irc-stream#options) for what they can be set to.

The whole module is built for request response to the bot, so it's not going to be able to pick up specific channel stuff unless you set participation chance to 100, but then you break the model. The trigger is a [catch-all](https://github.com/clux/cleverbot-irc/blob/ed7f1ba12fb56b49409a2f092b621195b0af271a/bot/clvr.js#L31) because every message you address to it will be responded to through clever. irc-stream bots are generally meant to only respond to messages addressed to them.

**Comment by manavortex** [comment]
Hi clux, 
I'm afraid you're two steps too far down the line for me - I've never worked with javascript before, so I'm having some difficulties reading it. In my above sample, I have identified ircStream as that what should have the bot, is that correct so far? 

You probably wrapped that tightly into the IO-stream, which makes me wonder - would you mind un-wrapping it a bit? Is that even possible? I don't really understand what kind of communication goes from where to were, and the fact that your objects are named differently from those in the API docs doesn't help. :D

**Comment by clux** [comment]
Well, ultimately you need to identify what you need to do. Register with nickserv is likely a case of:

```sh
cd cleverbot-irc
npm install nickserv --save
```

and add

```js
var NickServ = require('nickserv');
var nickserv = new NickServ('clvr', {
  password: 'hunter2',
  email: 'my@mail.com'
});
 
nickserv.attach('irc', ircStream.bot);
```

in the entry point. But I am not using, nor have I tested this. That stuff is unfortunately up to you.

> You probably wrapped that tightly into the IO-stream, which makes me wonder - would you mind un-wrapping it a bit?

The objects have well defined boundaries, and that's unlikely to change. It may just be the config that has the ability to set options for three modules that makes things confusing. You need to be more specific about what you want. It sounds like the irc-stream options above is what you want.

**Comment by clux** [comment]
Going to close this as it's rotted.
