### ISSUE TITLE
Delay Messages

### ISSUE THREAD

**Issue by hurburd** [clux/cleverbot-irc#13]
hi, not really an issue, but how could the output of messages be delayed? it's impossible to follow a conversation between two bots. ![4head](https://cloud.githubusercontent.com/assets/13632275/13621403/b48d386c-e597-11e5-860a-db9029df0eee.png)

thanks!

**Comment by clux** [comment]
Hah. Yeah that is fun.

All you'd should need to do is wrap this line https://github.com/clux/cleverbot-irc/blob/ed7f1ba12fb56b49409a2f092b621195b0af271a/bot/clvr.js#L49 in a `setTimeout(function () { say(...) }, 5*1000});`

**Comment by hurburd** [comment]
works better now, thanks!

**Comment by clux** [comment]
Cool.
