### ISSUE TITLE
Is there a way use this Cleverbot without connecting to the master server?

### ISSUE THREAD

**Issue by antdude** [clux/cleverbot-irc#14]
Just internal IRC server and no connection to outside. Just using local data files for Cleverbot.

**Comment by clux** [comment]
No, that seems impossible at the moment. The AI behind the site is not open, and the only interfaces that currently exist rely on making http requests. The guys behind [cleverbot.io](https://cleverbot.io/) has to make an offline version.

**Comment by antdude** [comment]
Thank you for the quick answer, Clux. :)
