### ISSUE TITLE
 suddenly the bot only writes < html >

### ISSUE THREAD

**Issue by mascalzone** [clux/cleverbot-irc#15]
hello , I am a regular user , I am not an expert in informatic .
I installed the bot on vps and I did enter my irc channel.
For a few days it worked fine .
Now only writes < html >
I thought the Cleverbot site had banned the address of vps and I tried to install it on another VPS with a different address , but it is the same result .

Someone can ' explain what happened and if there is a solution ?
I'd like it to work , I think it's a great job .
thanks to those who respond .

**Comment by clux** [comment]
Has happened before when cleverbot changes their usage parameters. Looks like this has happened again or the service is down. Current results from using `cleverbot-node` (the scraper we rely on):

```js
> var CB = require('cleverbot-node')
undefined
> clever = new CB()
> CB.prepare(function() { clever.write('hi there', function (data) { console.log(data); }); });
undefined
> { message: '<html>',
  sessionid: '\n<head><title>404 Not Found</title></head>',
  logurl: '\n<body bgcolor="white">',
  vText8: '\n<center><h1>404 Not Found</h1></center>',
  vText7: '\n<hr><center>nginx/1.6.2 (Ubuntu)</center>',
  vText6: '\n</body>',
  vText5: '\n</html>',
  vText4: '\n' }
```

**Comment by clux** [comment]
Service is up, scraper needs updating :/

See https://github.com/fojas/cleverbot-node/issues/6

**Comment by mascalzone** [comment]
I had guessed.
there is a solution to this problem?
It considers that they are ignorant on the computer.
It is really a pity that does not work anymore '.
There's nothing to do????

**Comment by clux** [comment]
You can try re-raising an issue over there. I don't really have time to look at it.

**Comment by mascalzone** [comment]
if you tell me what to look for , Dover and look for Where to go to change the bot , I 'll try .
I know there'll be able ' , but I hate being without doing anything .

**Comment by clux** [comment]
The problem is somewhere in [cleverbot.js](https://github.com/fojas/cleverbot-node/blob/master/lib/cleverbot.js). That needs to work by itself before the bot will work.

**Comment by mascalzone** [comment]
hahahaha . ok
I have to resign ourselves to lose this magnificent bot .
They are too ignorant not able ' d only ever restore it .
Thanks anyway.

**Comment by mascalzone** [comment]
Hello. Whereas I can not fix this problem I just have to hope for the release of a new release .
You can not tell me if there is the possibility of a release of a new release?
I like your work too .

**Comment by clux** [comment]
Thank you. I am sure someone will fix it eventually. I will comment on this issue if that happens.

**Comment by clux** [comment]
Tested this again today, mysteriously the bot works again. Seems there has been a patch bump in cleverbot-node that fixes this. :smile:

**Comment by mascalzone** [comment]
I tried to run , m not working . Always the same problem 4 < 8 { 21:36:08 } 8 4 > < 04 ~ [ STRONZIxsimo_me > IA ciao
 IA > [ STRONZIxsimo_me : < html >

**Comment by clux** [comment]
Make sure you have updated your dependencies:

```sh
$ npm install
$ npm ls --depth=0
cleverbot-irc@1.1.4 /home/clux/repos/cleverbot-irc
├── cleverbot-node@0.2.2
├── confortable@1.0.0
├── gu@0.6.2
├── irc-colors@1.3.0
├── irc-stream@0.3.2
├── jscoverage@0.5.9
├── levenshtein@1.0.5
├── nodeunit@0.9.3
├── sulfur@1.0.1
├── suncalc@1.7.0
└── zalgolize@1.2.4
```

cleverbot-node@0.2.2 is the critical update.

**Comment by mascalzone** [comment]
Hello. I'm sorry , I'm not a computer expert .
I went in Cleverbot - irc folder and gave the npm install command , and then NPM --depth ls = 0
 It came out this ;
cleverbot-irc@1.1.4 / home / CLUX / repos / Cleverbot - irc
├── cleverbot-node@0.2.2
├── confortable@1.0.0
├── gu @ 0.6.2
├── irc-colors@1.3.0
├── irc-stream@0.3.2
├── jscoverage@0.5.9
├── levenshtein@1.0.5
├── nodeunit@0.9.3
├─ sulfur@1.0.1 ─
├── suncalc@1.7.0
└── zalgolize@1.2.4
 After I gave npm start , the bot connects to the IRC network , but always the same question he answers in this
IA > [ STRONZIxsimo_me : < html >
Did I do something wrong?

**Comment by mascalzone** [comment]
This is a second attempt , I came this ;

root@vps:~/cleverbot-irc# nmp install
-bash: nmp: command not found
root@vps:~/cleverbot-irc# npm ls --depth=0
cleverbot-irc@1.1.4 /root/cleverbot-irc
├── cleverbot-node@0.2.1
├── confortable@1.0.0
├── coveralls@2.11.9 extraneous
├── crypto@0.0.3
├── gu@0.6.2
├── irc-colors@1.2.1
├── irc-stream@0.3.2
├── jscoverage@0.5.9
├── levenshtein@1.0.5
├── nodeunit@0.9.1
├── sulfur@1.0.1
├── suncalc@1.7.0
└── zalgolize@1.2.4

npm ERR! extraneous: coveralls@2.11.9 /root/cleverbot-irc/node_modules/coveralls

**Comment by mascalzone** [comment]
root@vps:~/cleverbot-irc# ls
LICENSE  README.md  bot  bot-cov  clvr-gu.js  daemonize  irc.js  node_modules  nohup.out  package.json  test
root@vps:~/cleverbot-irc# ls
