### ISSUE TITLE
not sure it works anymore

### ISSUE THREAD

**Issue by dchmelik** [clux/cleverbot-irc#17]
I tried version 1.1.2, but 1.1.4, I join to a channel, say hi, and it just is silent for many minutes...

**Comment by clux** [comment]
Seems likely, haven't tried it in the bit, and the underlying cleverbot module appears to have moved on to use the proper API keys: https://github.com/fojas/cleverbot-node

It's likely needs a cleverbot-node bump in the package.json and a little bit of logic in clvr.js to use a configured token from our config.

I am on holiday atm, but feel free to goof around. I'll merge a sensible PR :)
